### ISSUE TITLE
26-http-errors.html : error state not required

### ISSUE THREAD

**Issue by stressedtyagi** [kentcdodds/beginners-guide-to-react#11]
### In HTML file 26-http-error.html
Since we are hardcoding the message as well error message corresponding to each status we are getting via the `status` state. 
So we don't require an `error` state to separately manage the error that we are getting from the `fetchPokemon() ` API call. I think keeping the `error` state is redundant code, solution could be to remove this state or use that error message to display it to the user in some way.

**Comment by kentcdodds** [comment]
Makes sense! Thanks for bringing this up. I'm not making any changes to this repository though because we want to keep it the same as the videos. Thanks anyway :)

**Comment by stressedtyagi** [comment]
Thanks for responding, I understand you can't change the code, your response also clarified my doubt. Also thanks a lot for creating this beginner course on egghead, I really liked it. It cleared all my doubts and helped me a lot in revising all the concepts of React. Best fast and to-the-point course I found online for beginners in React.
