### ISSUE TITLE
Pokmon API is not available anymore: https://graphql-pokemon.now.sh

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/beginners-guide-to-react#3]
This issue: https://github.com/kentcdodds/react-hooks/issues/28 applies to this project as well. Specifically:

This API is no longer working:

"ZEIT Now 1.0 is being shut down. As part of this, all ZEIT Now 1.0 Deployments will become inaccessible."

The owner of the repo has been notified already: lucasbento/graphql-pokemon#13

But it seems unlikely anything will happen here. I tried to get the project up and running so I could deploy it elsewhere but that didn't work right away and I didn't have the time to figure out what was wrong with their project.

**Comment by kentcdodds** [comment]
The solution for this project and others is to use MSW (which thankfully has a UMD export, thank you @kettanaito!!). So I was able to easily add a script tag for that and add a new script tag for a simple script that just sets it up (as well as the service worker itself).

Closed in https://github.com/kentcdodds/beginners-guide-to-react/commit/e0cefaa459c9db8520984d8895483d30df9f552d

Works great.

**Comment by ravsing123** [comment]
Is there any work around this ?
