### ISSUE TITLE
How about give MIT license on this guide repository?

### ISSUE THREAD

**Issue by scurrymode** [kentcdodds/beginners-guide-to-react#8]
Thank you for your great guide to react.

You said on twitter this lecture will be free forever. (It was amazing.)
I found this repository has no license which means it is default license on it.
Many people already fork this guide sources.

How about give MIT license on this repository. To many other people learn free and feel free to share this great lecture and source to introduce react fundamentals.

**Comment by kentcdodds** [comment]
License added! Thanks ☺️
