### ISSUE TITLE
Changing the graphql query does not give a network error

### ISSUE THREAD

**Issue by kawpii** [kentcdodds/beginners-guide-to-react#9]
Thank you very much for the free course, really good material!

-----
In master branch [25-http.html](https://github.com/kentcdodds/beginners-guide-to-react/blob/main/25-http.html)

if you change the `name` to `nam` like in the [video](https://egghead.io/lessons/react-handle-http-errors-with-react), it does not give a network error but still provide correct response for the pokemon name (ex: mew)

```
const pokemonQuery = `
        query PokemonInfo($name: String) {
          pokemon(name: $name) {
            id
            number
            name
            attacks {
              special {
                nam
                type
                damage
              }
            }
          }
        }`;
```

Why is that I am confused?

**Comment by kentcdodds** [comment]
In an effort to make this workshop work completely offline (and not rely on 3rd parties), we actually use a service worker to intercept all network requests and handle them ourselves in this file: https://github.com/kentcdodds/beginners-guide-to-react/blob/main/pokemon-api.js

It seems you've found a bug in our implementation (PRs welcome).

I made this change after the videos were created, so that's why you're seeing the difference.

**Comment by kawpii** [comment]
> It seems you've found a bug in our implementation (PRs welcome).

I looked in to this, it seems `pokemon-api.js` do no care about the graphql query at all, it just get a object by name.

`mswjs` do not do data schema validation internally so the [mockServiceWorker.js graphql error ](https://github.com/kentcdodds/beginners-guide-to-react/blob/main/mockServiceWorker.js#L159) just do syntax validation.

I tried to include [graphql-js](https://github.com/graphql/graphql-js) using upkg to use [graphql/validation](https://graphql.org/graphql-js/validation/) in order to validate the graphql schema but facing an error

` <script src="https://unpkg.com/graphql"></script>`

```
Uncaught ReferenceError: exports is not defined
    at graphql:3
```

probably `graphql-js `is not supported through CDNs.

Writing custom graphql schema validation is tricky.

**Comment by kentcdodds** [comment]
Ah, I see. Yeah, that's a bit of a bummer. I'm afraid we'll probably just have to live with this :-/

**Comment by kawpii** [comment]
I'll close this now then.
